name: Release Android App
on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Sign Android release
    name: build android app
    steps:
      - uses: actions/checkout@v2
      - uses: sparkfabrik/android-build-action@v1.0.0
        with:
          project-path: .
          gradle-task: assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      # https://github.com/marketplace/actions/upload-files-to-a-github-release#input-variables
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.sign_app.outputs.signedReleaseFile }}
          tag: ${{ github.ref }}
